matrix:
  include:
    - language: java
      jdk: openjdk8
      script: mvn clean package
      env:
        - DEPLOY_TARGET=backend

    - language: node_js
      node_js:
        - "node"
      script: ./configuration/frontend.sh ${TRAVIS_BRANCH}
      env:
        - DEPLOY_TARGET=frontend

before_deploy:
- mkdir -p $HOME/.ssh
- cp $TRAVIS_BUILD_DIR/travis-key $HOME/.ssh/travis-key
- cp $TRAVIS_BUILD_DIR/ssh-config $HOME/.ssh/config

before_install:
- openssl aes-256-cbc -K $encrypted_6e2695e2c6f8_key -iv $encrypted_6e2695e2c6f8_iv
  -in secrets.tgz.enc -out secrets.tgz -d
- tar xzf secrets.tgz

deploy:
- provider: script
  skip_cleanup: true
  script: ./configuration/deploy.sh preprod ${DEPLOY_TARGET}
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: ./configuration/deploy.sh prod ${DEPLOY_TARGET}
  on:
    branch: master
    tags: true
- provider: script
  skip_cleanup: true
  script: ./configuration/deploy.sh dev ${DEPLOY_TARGET}
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^feature/.*$"
- provider: script
  skip_cleanup: true
  script: ./configuration/deploy.sh dev ${DEPLOY_TARGET}
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^hotfix/.*$"