language: java
script: mvn package
services: postgresql

before_deploy:
- mkdir -p $HOME/.ssh
- cp $TRAVIS_BUILD_DIR/travis-key $HOME/.ssh/travis-key
- cp $TRAVIS_BUILD_DIR/ssh-config $HOME/.ssh/config
- tar czf $TRAVIS_BUILD_DIR/TrollsGames-${TRAVIS_TAG}.tgz configuration target/*.jar

before_install:
- openssl aes-256-cbc -K $encrypted_6e2695e2c6f8_key -iv $encrypted_6e2695e2c6f8_iv
  -in secrets.tgz.enc -out secrets.tgz -d
- tar xzf secrets.tgz

before_script:
- psql -c 'create database trolls_test;' -U postgres

deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: NlGbcX6AgwWaMjPtpG/+Hh89X2jKbfdswxDTjbHTNeEzf5znQTB8doCGXRrQPu5u7LPQofDMh2DEclCmne7146WTHzAtufR36igJ42QNR03xhq82doEeDldOC3l02kM7ro7YMWw9qoj9L/8Qmpx5A7hh1Ij3gKMk2jl2un3bYSw3DmDXivycL5E3osCrG2lzupzQQSdCvpfObQ24y1xz9/ZGRW+uaqtjmUX4hxyce36vGyeR2Vii7fHXCKdknIU0IComVpOdnkpbWAD0UGxbNf+ebbGJ+st6ouhDHakgpWjQ5lZucS+w/7wZTlxjnLfyy8MslK1c57VI5SAJ9aT9ZORGho6YZ8d5dy88dYH9b+Ypi5TZY433nFzxNOeZRO9FQ/ymVVEQu1nd4rhWHK4QrQYljgFgrdSib6uTfwk4MfgTaogWJGuHMNIOEOiiBt1nHDj2eRRfxF645ucAA/Tw9/VpQTyt6GEPxbvqjFmTaN4AwGQiI63WzBweZtAZik12a2FvXvjEMXJlhhy5FqWD2J+2fQre7q9P68aGI8tcpVQd9g6t5yFlzeB6MhlcH7a3Gd4FJpn2ter+dib33uoj7lvhr+1biiqXR8unYok3kqrovLIKZhFVXBBMadO2aSVk+9RGcgbHqnnJ5HATIQaimtJWKURbydJOGlUy2QsRJPM=
  file: $TRAVIS_BUILD_DIR/TrollsGames-${TRAVIS_TAG}.tgz
  on:
    branch: master
    repo: massix/TrollsGamesServer
    tags: true
- provider: heroku
  api_key:
    secure: uiDL9eXqp5KPj/xRP4xKORgyNsKnYWOMtD2+bP/o+YLUXbG/Z0QrCqNmKd2KIHgrysqKee47Nib89+sAdHb0Hm/jklD0GoKlNgYnXWjhqAMbkFhtgNQSqJ1mDZ6vx0+U2g9xNylKPub7iY+jV2Z/ook1Z5zHb384hGMLBuIRU1ChNwQwhFlkKmNQxBe7TSegByJVEigCq5TPg6eSSE50M/gC7an6oenbJWmmjFoUgF2aLp7BdSXxJHnhNseUzs7XbmY7k7BBD6E9yWUTg5GsyswWeZv+sIeVI6j4fdrlCnJGwyRl5hkpRcXSzsC8vhr4vMtZfNMgPvWHY0MY14YX8t0UajG0PgP4tsB4P2H/L14xo+aGt4ogNrtqcoBpP43NuYzmpPb6j3aws8isOwyNi63i+ysCyy74GHn6+fnGn+rvs3IXEq/Ihd9tLlesX+EVfyeyC3cC4ggvNUEXm+5yCYcD4LAsHQOQjIbdgNP4+3WMqzFpy37i6Wm82cmRu1tP87AvlW06ApPJTgwmF/PikO4Zv1cFbcP+m1Ij7KMNwuEKqUTQ06rex7eBIqkVN6GPlMjJ5feO7flXpAzGoOcJUEKVcFM75qnjs5LqRC8k/RPISnZrIQUeXgz6Gk0StzVwDSNYCj3vvAFPmUAtkRV4kNkACN2kuVjOuvE/y4J8TdI=
  app: trolls-server
  on:
    branch: master
    repo: massix/TrollsGamesServer
    tags: true
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master
    tags: true