language: java
script: mvn package

before_deploy:
- mkdir -p $HOME/.ssh
- cp $TRAVIS_BUILD_DIR/travis-key $HOME/.ssh/travis-key
- cp $TRAVIS_BUILD_DIR/ssh-config $HOME/.ssh/config

before_install:
- openssl aes-256-cbc -K $encrypted_6e2695e2c6f8_key -iv $encrypted_6e2695e2c6f8_iv
  -in secrets.tgz.enc -out secrets.tgz -d
- tar xzf secrets.tgz

deploy:
- provider: script
  skip_cleanup: true
  script: ./configuration/deploy.sh preprod
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: ./configuration/deploy.sh prod
  on:
    branch: master
    tags: true